### ISSUE TITLE
Add delete method to Storage

### ISSUE THREAD

**Issue by olegmoz** [artipie/asto#110]
Delete method should remove particular value from Storage by key. If value not exists then the method should fail. So if it is a file storage it should not allow to delete folders, only files.

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by 0crat** [comment]
Job `gh:artipie/asto#110` is not assigned, can't get performer
