### ISSUE TITLE
Use generic Storage tests for FileStorage

### ISSUE THREAD

**Issue by olegmoz** [artipie/asto#113]
There are multiple Storage tests that are applicable for any Storage. Using them for FileStorage will improve test coverage and may reduce test code duplication

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by 0crat** [comment]
Job `gh:artipie/asto#113` is not assigned, can't get performer
