### ISSUE TITLE
Add ctor to From with UUID 

### ISSUE THREAD

**Issue by dgarus** [artipie/asto#114]
Add ctor to com.artipie.asto.Key.From that accept the UUID parameter.
That ctor could be used in com.artipie.composer.http.Root#put

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by g4s8** [comment]
@dgarus I'm not sure that we need such constructor now. Where it can be used?

**Comment by dgarus** [comment]
@g4s8 There are few places in artipie projects:
[NewPackage#put](https://github.com/artipie/nuget-adapter/blob/d345aff94b24b670eb5d7723e2316c07f9686ad1/src/main/java/com/artpie/nuget/http/PackagePublish.java#L99)
planning in [Root#put](https://github.com/artipie/composer-adapter/blob/d38cde34be7a6333c7f1d54c3e210901399a249f/src/main/java/com/artipie/composer/http/Root.java#L67)

So I think it may be a common way to create key.

**Comment by g4s8** [comment]
@olegmoz please check this issue, do we need such constructor?

**Comment by olegmoz** [comment]
@g4s8 true, I am building temporary keys for uploads from UUIDs, but I do not think that approach deserves to be generalized. So I'd rather say we do not need special constructor for that

**Comment by g4s8** [comment]
It seems we do not really need such constructor for `Key`
