### ISSUE TITLE
Google Storage support

### ISSUE THREAD

**Issue by Guseyn** [artipie/asto#119]

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by Sammers21** [comment]
Google cloud storage is S3 compatible, that is why I would implement dedicated support for it

**Comment by g4s8** [comment]
Google storage supports S3 API.

**Comment by 0crat** [comment]
Job `gh:artipie/asto#119` is not assigned, can't get performer
