### ISSUE TITLE
FileStorage incorrectly processes list(Key.ROOT) call

### ISSUE THREAD

**Issue by brastak** [artipie/asto#131]
Calculation of path prefixes works incorrectly when Key.ROOT is passed to the list method.

Let's assume:
- base folder is /storage
- artifact is persisted in /storage/artifact.bin

When FileStorage.list() is called for the ROOT, than prefix length is 8 ("/storage".length() + "".length()) and the rest part of the path is /artifact.bin. We can not build key for this string and method fails (it splits to ["", "artifact.bin"] array and key can not contain empty parts).

So we need either support Key construction from the string with the leading "/" or change FileStorage to handle Key.ROOT a special way

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by g4s8** [comment]
@rultor release, tag=`0.16.1`

**Comment by 0crat** [comment]
Job `gh:artipie/asto#131` is not assigned, can't get performer
