### ISSUE TITLE
Need to use List instead of Collection in the Key Constructror

### ISSUE THREAD

**Issue by brastak** [artipie/asto#134]
https://github.com/artipie/asto/blob/e05853704c3dfdb93c5ecb48a3c2df25101632d6/src/main/java/com/artipie/asto/Key.java#L127

Ordering is important here, we should not work with HashSet<String>

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by 0crat** [comment]
Job `gh:artipie/asto#134` is not assigned, can't get performer
