### ISSUE TITLE
Remove duplication of code for ByteBuffer concatination

### ISSUE THREAD

**Issue by olegmoz** [artipie/asto#135]
It is very common in tests (and in production code as well), to concatenate `Content` which is a `Publisher<ByteBuffer>` into single byte array. This operation requires a lot of code which is now copied and pasted across all Artipie modules.

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by 0crat** [comment]
Job `gh:artipie/asto#135` is not assigned, can't get performer
