### ISSUE TITLE
Implement SubStorage / VirtualStorage conception

### ISSUE THREAD

**Issue by brastak** [artipie/asto#139]
Storages can be shared by repositories. But repositories don't want to have mixed content. So, storage paths of the different repositories will be separated by Key prefixes.
But we have to manage this prefixes when request is processed. Often both of Slice adapter and Repository itself must add/remove Key prefixes info to the request context.
There is alternative - to use SubStorage / VirtualStorage. The idea is the same as [Sub Configurations](http://commons.apache.org/proper/commons-configuration/userguide/howto_hierarchical.html#Sub_Configurations). Each repository works with own Virtual Storage and addresses it from the Root. Virtual Storage inside translates internal Keys to external and calls required methods of the real Storage.

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by 0crat** [comment]
The job [#139](https://github.com/artipie/asto/issues/139) assigned to @g4s8[/z](https://www.0crat.com/u/g4s8), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/2079d773-8757-4621-a8fe-d840bd79f657); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by g4s8** [comment]
@brastak please check #180 PR

**Comment by 0pdd** [comment]
@brastak the puzzle [#181](https://github.com/artipie/asto/issues/181) is still not solved.

**Comment by g4s8** [comment]
@rultor release, tag=`0.20.2`

**Comment by g4s8** [comment]
@rultor release, tag=`0.20.2`

**Comment by g4s8** [comment]
@rultor release, tag=`0.20.2`

**Comment by 0crat** [comment]
Job `gh:artipie/asto#139` is not assigned, can't get performer

**Comment by 0pdd** [comment]
@brastak the puzzle [#unknown]() is still not solved.

**Comment by 0pdd** [comment]
@brastak the only puzzle [#181](https://github.com/artipie/asto/issues/181) is solved here.
