### ISSUE TITLE
Add abstract decorator for Storage

### ISSUE THREAD

**Issue by olegmoz** [artipie/asto#144]
It is inconvenient to create implementations of Storage composed of other implementations without an abstract decorator class

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by 0crat** [comment]
Job `gh:artipie/asto#144` is not assigned, can't get performer

**Comment by olegmoz** [comment]
@g4s8 please make a release with this issue resolved, I would like to use it in Docker adapter

**Comment by g4s8** [comment]
@rultor release, tag=`0.17.1`
