### ISSUE TITLE
Add Storage method to read value size without all of it's content

### ISSUE THREAD

**Issue by olegmoz** [artipie/asto#146]
There are cases when only length of value is needed and it is not required to read all of it's content (such as getting layer metadata in Docker registry API, see https://docs.docker.com/registry/spec/api/#pushing-an-image)

**Comment by 0crat** [comment]
Job `gh:artipie/asto#146` is not assigned, can't get performer

**Comment by g4s8** [comment]
@rultor release, tag=`0.18`
