### ISSUE TITLE
InMemory value method not working

### ISSUE THREAD

**Issue by Guseyn** [artipie/asto#153]
In npm adapter I tried to do following with in-memory storage:

```java
    @Test
    public final void uploadWorksProperly()
        throws IOException, InterruptedException, ExecutionException {
        final Vertx vertx = Vertx.vertx();
        final int port = this.randomPort();
        final Storage storage = new InMemoryStorage();
        final VertxSliceServer server = new VertxSliceServer(
            vertx,
            new NpmSlice(
                storage
            ),
            port
        );
        server.start();
        final WebClient web = WebClient.create(vertx);
        final int code = web.put(port, "localhost", "/package")
            .rxSendBuffer(Buffer.buffer(
                "{ \"versions\":  {\"1.0.1\": {}, \"1.0.4\": {}, \"1.0.2\": {}} }"
            ))
            .blockingGet()
            .statusCode();

        web.close();
        server.close();
        vertx.close();
        storage.value(new KeyFromPath("/package")).get();
    }
```

and last line with `storage.value(new KeyFromPath("/package")).get();` simply waits forever and never completes.

On the other hand `FileStorage` works fine.

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by Guseyn** [comment]
@olegmoz I would recommend another adapter for reproducing the bug, as I tested it with fixed npm adapter. But it seems it will not work for any of properly working adapters.

**Comment by 0crat** [comment]
The job [#153](https://github.com/artipie/asto/issues/153) assigned to @olegmoz[/z](https://www.0crat.com/u/olegmoz), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/93be5a28-3f6d-4d10-b22d-5147e7576815); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); @olegmoz[/z](https://www.0crat.com/u/olegmoz) is not a member of this project yet, but they can request to join, as [§1](http://www.zerocracy.com/policy.html#1) explains; there will be no monetary reward for this job

**Comment by olegmoz** [comment]
@Guseyn Ok, so I simplified a little bit the test, because all the class needed in example are not in master branch still:
```
    @Test
    public final void uploadWorksProperly() throws InterruptedException, ExecutionException {
        final Storage storage = new InMemoryStorage();
        new NpmSlice(new Npm(storage), storage).response(
            "PUT /package",
            Collections.emptySet(),
            Flowable.just(
                ByteBuffer.wrap(
                    "{ \"versions\":  {\"1.0.1\": {}, \"1.0.4\": {}, \"1.0.2\": {}} }".getBytes()
                )
            )
        );
        storage.value(new KeyFromPath("/package")).get();
    }
```
And the test does not hang, it crashes with IllegalArgumentException which I guess is expected.
Do you think this test simplification is wrong?

**Comment by Guseyn** [comment]
@olegmoz It's hard to say, I guess it because you don't use vertx server and maybe the with our vertx server implementation, but it's hard to say. I think you should test it with other proper working slices or make checkout from branch https://github.com/Guseyn/npm-adapter/tree/upload-slice-test

**Comment by olegmoz** [comment]
@Guseyn thanks for the link! Can reproduce the issue now

**Comment by olegmoz** [comment]
@Guseyn the reason test passes with FileStorage is that FileStorage creates file before it's content is written (and there no content comes to Storage in this test).
Added issue for that: https://github.com/artipie/npm-adapter/issues/46
Fixed that InMemoryStorage blocks forever when endless Content is being saved - getting this fixed in created PR for this issue.

**Comment by Guseyn** [comment]
@olegmoz cool, thanks, guess all these rx java shit is still magic to me

**Comment by Guseyn** [comment]
@g4s8 I think, I can close this ticket as it's resolved

**Comment by 0crat** [comment]
Job [#153](https://github.com/artipie/asto/issues/153) is not in the agenda of @olegmoz[/z](https://www.0crat.com/u/olegmoz), can't set title

**Comment by 0crat** [comment]
@sereshqua[/z](https://www.0crat.com/u/sereshqua) please review this job completed by @olegmoz[/z](https://www.0crat.com/u/olegmoz), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by sereshqua** [comment]
@0crat quality good

**Comment by 0crat** [comment]
Job [#153](https://github.com/artipie/asto/issues/153) is not in the agenda of @olegmoz[/z](https://www.0crat.com/u/olegmoz), can't set title
