### ISSUE TITLE
Storages syncronization

### ISSUE THREAD

**Issue by Sammers21** [artipie/asto#160]
There is a use case in gem adapter, which requires synchronization of two storages: local temp dir with metadata and underlying primary storage. 

I would like to request to add a Storage synchronization primitive.

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by g4s8** [comment]
@Sammers21 yes, it may be useful

**Comment by 0pdd** [comment]
@Sammers21 the puzzle [#162](https://github.com/artipie/asto/issues/162) is still not solved.

**Comment by 0pdd** [comment]
@Sammers21 the puzzle [#168](https://github.com/artipie/asto/issues/168) is still not solved; solved: [#162](https://github.com/artipie/asto/issues/162).

**Comment by 0pdd** [comment]
@Sammers21 all 2 puzzles are solved here: [#162](https://github.com/artipie/asto/issues/162), [#168](https://github.com/artipie/asto/issues/168).

**Comment by 0crat** [comment]
Job `gh:artipie/asto#160` is not assigned, can't get performer
