### ISSUE TITLE
Copy.java:39-41: Implement Copy class. This class...

### ISSUE THREAD

**Issue by 0pdd** [artipie/asto#162]
The puzzle `160-2edb9ba4` from #160 has to be resolved: 

https://github.com/artipie/asto/blob/82add0ff76d4c10b32b3e908a23f064be54f0cc7/src/main/java/com/artipie/asto/Copy.java#L39-L41

The puzzle was created by @Sammers21 on 24-Apr-20. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by 0crat** [comment]
The job [#162](https://github.com/artipie/asto/issues/162) assigned to @sammers21[/z](https://www.0crat.com/u/sammers21), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/793757ec-4bca-49ce-a6d9-83b40c74c996); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); @sammers21[/z](https://www.0crat.com/u/sammers21) is not a member of this project yet, but they can request to join, as [§1](http://www.zerocracy.com/policy.html#1) explains; we should be aware that @sammers21[/z](https://www.0crat.com/u/sammers21) is on vacation; this ticket may be delayed; there will be no monetary reward for this job

**Comment by 0pdd** [comment]
The puzzle `160-2edb9ba4` has disappeared from the source code, that's why I closed this issue.

**Comment by 0crat** [comment]
Job [#162](https://github.com/artipie/asto/issues/162) is not in the agenda of @sammers21[/z](https://www.0crat.com/u/sammers21), can't set title

**Comment by 0crat** [comment]
Job [#162](https://github.com/artipie/asto/issues/162) is not in the agenda of @sammers21[/z](https://www.0crat.com/u/sammers21), can't set title

**Comment by 0crat** [comment]
@sereshqua[/z](https://www.0crat.com/u/sereshqua) please review this job completed by @sammers21[/z](https://www.0crat.com/u/sammers21), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by sereshqua** [comment]
@0crat quality good
