### ISSUE TITLE
RxCopy.java:37-39: Implement RxCopy class. This class...

### ISSUE THREAD

**Issue by 0pdd** [artipie/asto#168]
The puzzle `160-24b7b6f9` from #160 has to be resolved: 

https://github.com/artipie/asto/blob/aeda84b9bbb6b08b2342b91552a1d24f9c4f2a9b/src/main/java/com/artipie/asto/rx/RxCopy.java#L37-L39

The puzzle was created by @g4s8 on 27-Apr-20. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by 0pdd** [comment]
The puzzle `160-24b7b6f9` has disappeared from the source code, that's why I closed this issue.

**Comment by g4s8** [comment]
@rultor release, tag=`0.19`

**Comment by g4s8** [comment]
@rultor release, tag=`0.19`

**Comment by g4s8** [comment]
@rultor release, tag=`0.19.1`
