### ISSUE TITLE
File storage is too slow

### ISSUE THREAD

**Issue by g4s8** [artipie/asto#171]
Copying 1Gb file via `FileStorage` takes about 10-13 seconds, while copying the same file from and to same disks and filesystems takes less than 1 second. Let's fix it.

**Comment by 0crat** [comment]
The job [#171](https://github.com/artipie/asto/issues/171) assigned to @g4s8[/z](https://www.0crat.com/u/g4s8), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/3be7bde9-fe9f-4a1c-bc48-6e371c8b4107); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by g4s8** [comment]
@rultor release, tag=`0.20`

**Comment by g4s8** [comment]
Fixed in `0.20`

**Comment by 0crat** [comment]
Job `gh:artipie/asto#171` is not assigned, can't get performer
