### ISSUE TITLE
No test coverage

### ISSUE THREAD

**Issue by g4s8** [artipie/asto#175]
Enabled test coverage limits and add codecov badge

**Comment by 0crat** [comment]
The job [#175](https://github.com/artipie/asto/issues/175) assigned to @g4s8[/z](https://www.0crat.com/u/g4s8), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/231fcc86-fb93-445a-8823-cf1281610020); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job
