### ISSUE TITLE
Deploy snapshots

### ISSUE THREAD

**Issue by g4s8** [artipie/asto#178]
Deploy snapshots to Artipie central

**Comment by 0crat** [comment]
The job [#178](https://github.com/artipie/asto/issues/178) assigned to @g4s8[/z](https://www.0crat.com/u/g4s8), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/650301a2-54b6-44cf-8f5e-c6eb4dbe06b8); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by g4s8** [comment]
@rultor release, tag=`0.20.1`

**Comment by g4s8** [comment]
@rultor release, tag=`0.20.3`

**Comment by 0crat** [comment]
Job was finished in 47 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))

**Comment by g4s8** [comment]
@rultor release, tag=`0.20.3`

**Comment by g4s8** [comment]
@rultor release, tag=`0.20.3`
