### ISSUE TITLE
Storage operations logging

### ISSUE THREAD

**Issue by olegmoz** [artipie/asto#182]
To better understand what happens in integration tests and in production it would be nice to have `LoggingStorage` that delegates all operations to other `Storage` implementations and logs them.

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by 0crat** [comment]
Job `gh:artipie/asto#182` is not assigned, can't get performer

**Comment by olegmoz** [comment]
@rultor release, tag=`0.20.4`
