### ISSUE TITLE
Consider creating a Chunked Content of bytes

### ISSUE THREAD

**Issue by victornoel** [artipie/asto#187]
Sometimes it can be useful to create a `Content` from some bytes but having them chunked in the `Flowable`.

There is one implementation of it in the helm-adapter project of artipie, see `TgzArchive` class and https://github.com/artipie/helm-adapter/pull/25.

Consider pulling this implementation into asto for reuse everywhere needed in artipie and replacing it in helm-adapter.

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by g4s8** [comment]
@victornoel actually, the `Content` extends a `Publisher<ByteBuffer>` interface, which is already a chunked representation of a stream of byte buffers, so I don't really see a reason for additional chunking here.
