### ISSUE TITLE
Proper laziness in Rx components

### ISSUE THREAD

**Issue by Sammers21** [artipie/asto#189]
Not all the Rx components are properly lazy: when calling a method returning `Completable`, `Single`, etc., the actual computations should happen only after `subscribe()` call.

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by g4s8** [comment]
@Sammers21 can you explain the problem more detailed? I don't see any not lazy statement in `RxFile`.

**Comment by Sammers21** [comment]
@g4s8, when you call a method returning `Completable`, `Single`, ... the actual computations should happen only after `subscribe()` call.

**Comment by 0crat** [comment]
Job `gh:artipie/asto#189` is not assigned, can't get performer
