### ISSUE TITLE
Concatenation class is extremely slow on reading large files

### ISSUE THREAD

**Issue by brastak** [artipie/asto#191]
The reason is here:
https://github.com/artipie/asto/blob/427aaa12208a5952d3ae33e4a59ae1e7e71dc83a/src/main/java/com/artipie/asto/Concatenation.java#L63-L65

Let's assume that we are reading 100+MB file by the chunks of 8 KB. When reading is close to finish, we allocate new ~100MB buffer on every iteration. Reading file fragment from 100MB to 101MB produces ~ 128 * 100MB = >12GB memory consumption.

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by 0crat** [comment]
The job [#191](https://github.com/artipie/asto/issues/191) assigned to @brastak[/z](https://www.0crat.com/u/brastak), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/b597784b-79b5-4689-9611-6a293323df0a); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); @brastak[/z](https://www.0crat.com/u/brastak) is not a member of this project yet, but they can request to join, as [§1](http://www.zerocracy.com/policy.html#1) explains; there will be no monetary reward for this job

**Comment by 0crat** [comment]
@brastak[/z](https://www.0crat.com/u/brastak) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by 0crat** [comment]
@sereshqua[/z](https://www.0crat.com/u/sereshqua) please review this job completed by @brastak[/z](https://www.0crat.com/u/brastak), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by sereshqua** [comment]
@0crat quality acceptable

**Comment by sereshqua** [comment]
@g4s8 @brastak we need to make sure issues creator and issue performer are 2 different persons
