### ISSUE TITLE
S3Storage.java:67-71: Too many methods in `S3Storage`...

### ISSUE THREAD

**Issue by 0pdd** [artipie/asto#196]
The puzzle `193-ee41fbc9` from #193 has to be resolved: 

https://github.com/artipie/asto/blob/23201287aefb4b520aa2a9f70f8667014f750b05/src/main/java/com/artipie/asto/s3/S3Storage.java#L67-L71

The puzzle was created by @olegmoz on 04-Jun-20. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by victornoel** [comment]
@g4s8 I think you assigned to me instead of 0crat :)

**Comment by andreoss** [comment]
@0crat await #299

**Comment by andreoss** [comment]
@0crat wait for #299

**Comment by 0crat** [comment]
> @0crat await #299  ([here](https://github.com/artipie/asto/issues/196#issuecomment-774536493))

@andreoss Can't understand "await", try one of these:
  - `assign` Assign a performer to this issue
  - `boost` Set a boost for the job
  - `continue` Remove a job's impediment
  - `elect` Trigger election for ticket
  - `hello` Just say hello
  - `in` Register this issue in scope (WBS)
  - `out` Close the order and remove this job from scope
  - `pay` Pay a user some extra cash
  - `quality` Review a task
  - `resign` Resign from this issue
  - `status` Check the status of the job
  - `version` Print current version of the bot
  - `wait` Register an impediment for a job

**Comment by 0pdd** [comment]
The puzzle `193-ee41fbc9` has disappeared from the source code, that's why I closed this issue.

**Comment by 0crat** [comment]
Job [#196](https://github.com/artipie/asto/issues/196) is not in the agenda of @andreoss[/z](https://www.0crat.com/u/andreoss), can't set title
