### ISSUE TITLE
Change FileStorage to make content() and size() unavailable until file uploaded completely

### ISSUE THREAD

**Issue by brastak** [artipie/asto#203]
The other implementations of the `Storage` behave this way, so we need to align `FileStorage` contract

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8), @olenagerasimova[/z](https://www.0crat.com/u/olenagerasimova) please, pay attention to this issue

**Comment by g4s8** [comment]
@brastak the possible solution would be to save content on upload to another file and move it to destination after complete, e.g. if we save `blob123` key to `FileStorage`, it saves data to `blob123.part` file and moves it to `blob123` file after complete. @artipie/contributors

**Comment by brastak** [comment]
@g4s8 yes, that's the way I want to do it. The question is: what's better - to use filename-based mask (like `.part` suffix you mentioned) or to generate random UUID? The first approach allows to find zombie uploads and link it with the desired files (I'm not sure that this is really useful). But the second way is easier to implement (what if you already have `file.part` in your Storage and this is final file name?)

**Comment by 0crat** [comment]
@olegmoz[/z](https://www.0crat.com/u/olegmoz) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by 0crat** [comment]
Job [#203](https://github.com/artipie/asto/issues/203) is not in the agenda of @olegmoz[/z](https://www.0crat.com/u/olegmoz), can't set title

**Comment by 0crat** [comment]
Job [#203](https://github.com/artipie/asto/issues/203) is not in the agenda of @olegmoz[/z](https://www.0crat.com/u/olegmoz), can't set title

**Comment by 0crat** [comment]
@sereshqua[/z](https://www.0crat.com/u/sereshqua) please review this job completed by @olegmoz[/z](https://www.0crat.com/u/olegmoz), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by sereshqua** [comment]
@0crat quality good

**Comment by g4s8** [comment]
@rultor release, tag=`0.23.1`
