### ISSUE TITLE
Publisher produced by `Storage.value` method should be readable once

### ISSUE THREAD

**Issue by olegmoz** [artipie/asto#204]
`S3Storage` and `InMemoryStorage` should return publishers that behave in same way. Now `S3Storage` produces publishers readable once and publisher from `InMemoryStorage` could be read multiple times.

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8), @olenagerasimova[/z](https://www.0crat.com/u/olenagerasimova) please, pay attention to this issue

**Comment by olegmoz** [comment]
@Sammers21 here is the issue I was talking about

**Comment by Sammers21** [comment]
> @Sammers21 here is the issue I was talking about

Got it.

@g4s8, assign it to me

**Comment by 0crat** [comment]
The job [#204](https://github.com/artipie/asto/issues/204) assigned to @sammers21[/z](https://www.0crat.com/u/sammers21), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/6314912c-e066-4274-aa12-4229301ed29e); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); @sammers21[/z](https://www.0crat.com/u/sammers21) is not a member of this project yet, but they can request to join, as [§1](http://www.zerocracy.com/policy.html#1) explains; we should be aware that @sammers21[/z](https://www.0crat.com/u/sammers21) is on vacation; this ticket may be delayed; there will be no monetary reward for this job

**Comment by 0pdd** [comment]
@olegmoz the puzzle [#206](https://github.com/artipie/asto/issues/206) is still not solved.

**Comment by 0crat** [comment]
@sammers21[/z](https://www.0crat.com/u/sammers21) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by 0pdd** [comment]
@olegmoz the only puzzle [#206](https://github.com/artipie/asto/issues/206) is solved here.

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8), @olenagerasimova[/z](https://www.0crat.com/u/olenagerasimova) please, pay attention to this issue

**Comment by olegmoz** [comment]
@Sammers21 it seems `FileStorage` produces publishers that could be read multiple times and there is no test to check this property

**Comment by 0crat** [comment]
Job [#204](https://github.com/artipie/asto/issues/204) is not in the agenda of @sammers21[/z](https://www.0crat.com/u/sammers21), can't set title

**Comment by 0crat** [comment]
GitHub issue is still open, won't close

**Comment by Sammers21** [comment]
@olegmoz, fixed in #210

**Comment by 0crat** [comment]
Job [#204](https://github.com/artipie/asto/issues/204) is not in the agenda of @sammers21[/z](https://www.0crat.com/u/sammers21), can't set title

**Comment by 0crat** [comment]
Job [#204](https://github.com/artipie/asto/issues/204) is not in the agenda of @sammers21[/z](https://www.0crat.com/u/sammers21), can't set title

**Comment by 0crat** [comment]
@sereshqua[/z](https://www.0crat.com/u/sereshqua) please review this job completed by @sammers21[/z](https://www.0crat.com/u/sammers21), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by sereshqua** [comment]
@0crat quality good

**Comment by olegmoz** [comment]
@rultor release, tag=`0.23.2`

**Comment by olegmoz** [comment]
@rultor release, tag=`0.23.2`

**Comment by olegmoz** [comment]
@g4s8 rultor fails to release, could you look into this? Is it just sonatype down again or something else?

**Comment by g4s8** [comment]
@olegmoz it seems to be Sonatype error, it claims the staging rules with 504 Gateway Time-out:
```

[1;31mERRORm] Rule failure while trying to close staging repository with ID "comartipie-1187".
[1;31mERRORm]
[1;31mERRORm] Nexus Staging Rules Failure Report
[1;31mERRORm] ==================================
[1;31mERRORm]
[1;31mERRORm]
[1;31mERRORm] Cleaning up local stage directory after a Rule failure during close of staging repositories: []
[1;31mERRORm]  * Deleting context 229a643773d845.properties
[1;31mERRORm] Cleaning up remote stage repositories after a Rule failure during close of staging repositories: []
[1;31mERRORm]  * Dropping failed staging repository with ID "comartipie-1187" (Rule failure during close of staging repositories: []).

Waiting for operation to complete...
..

[1;31mERRORm] Remote staging finished with a failure: Staging rules failure!
```

**Comment by g4s8** [comment]
@rultor release, tag=`0.23.2`

**Comment by g4s8** [comment]
@rultor release, tag=`0.23.2`

**Comment by olegmoz** [comment]
@rultor release, tag=`0.23.2`
