### ISSUE TITLE
OneTimePublisher.java:35-37: Use one time publisher in...

### ISSUE THREAD

**Issue by 0pdd** [artipie/asto#206]
The puzzle `204-8901f06f` from #204 has to be resolved: 

https://github.com/artipie/asto/blob/f47f974914c63f4e198de37787b2df2eebff49f0/src/main/java/com/artipie/asto/OneTimePublisher.java#L35-L37

The puzzle was created by @g4s8 on 19-Jun-20. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8), @olenagerasimova[/z](https://www.0crat.com/u/olenagerasimova) please, pay attention to this issue

**Comment by 0pdd** [comment]
The puzzle `204-8901f06f` has disappeared from the source code, that's why I closed this issue.

**Comment by 0crat** [comment]
Job `gh:artipie/asto#206` is not assigned, can't get performer
