### ISSUE TITLE
Move ByteBufPublisher from docker to asto

### ISSUE THREAD

**Issue by olenagerasimova** [artipie/asto#212]
Docker-adapter has `ByteBufPublisher` class to read bytes from `Content`, I'd like to use this class in rpm (class `RpmITCase`) and pypi (`WheelSliceTest`) test scope. So, it seems reasonable to move this class from docker to asto.

**Comment by olenagerasimova** [comment]
@g4s8 @olegmoz what do you say?

**Comment by olegmoz** [comment]
@olenagerasimova nice idea, reading a flow of bytes into memory is useful in probably all adapters for parsing metadata files

**Comment by olenagerasimova** [comment]
@0crat assign me
