### ISSUE TITLE
Locker for the storage

### ISSUE THREAD

**Issue by olenagerasimova** [artipie/asto#214]
Implement storage locker to add lock to storage being updated, implementation should
1. check if storage is already locked
2. add lock key
3. release lock key

The simplest implementation can be found in rpm-adapter, check `com.artipie.rpm.misc.StorageLock`.
Consider introducing functionality to wait while storage is released.

**Comment by olenagerasimova** [comment]
@0crat assign @olegmoz

**Comment by olegmoz** [comment]
@g4s8 please assign me

**Comment by 0crat** [comment]
@olegmoz[/z](https://www.0crat.com/u/olegmoz) this job was assigned to you 7days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by 0crat** [comment]
Job [#214](https://github.com/artipie/asto/issues/214) is not in the agenda of @olegmoz[/z](https://www.0crat.com/u/olegmoz), can't set title
