### ISSUE TITLE
Last part of the key

### ISSUE THREAD

**Issue by olenagerasimova** [artipie/asto#215]
Let's introduce class to obtain last part of the key (filename), this feature is required both in python and rpm-adapters.

**Comment by olenagerasimova** [comment]
@0crat assign me

**Comment by 0crat** [comment]
Job was finished in 31 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))

**Comment by olenagerasimova** [comment]
@rultor release, tag=`0.23.3`
