### ISSUE TITLE
`FileStorage` returns content without unknown size

### ISSUE THREAD

**Issue by olegmoz** [artipie/asto#217]
`FileStorage` returns content without size specified. This was not the case some time ago and in my opinion all `Storage` implementations should return `Content` with known size

**Comment by 0crat** [comment]
You @olegmoz[/z](https://www.0crat.com/u/olegmoz) need to have one of these roles in order to do "Request order start": `ARC`, `PO`; I'm sorry to say this, but at the moment you've got no roles in this project

**Comment by olegmoz** [comment]
@rultor release, tag=`0.26`

**Comment by 0crat** [comment]
Job `gh:artipie/asto#217` is not assigned, can't get performer
