### ISSUE TITLE
StorageLock expiration

### ISSUE THREAD

**Issue by olegmoz** [artipie/asto#231]
When `StorageLock` is acquired by process and the process does not release it for whatever reason the lock cannot be obtained by any other process forever. Only manual deletion of lock from storage may solve the issue. The lock should expire automatically, after some timeout to allow timely release of the lock if some process didn't release it

**Comment by 0crat** [comment]
You @olegmoz[/z](https://www.0crat.com/u/olegmoz) need to have one of these roles in order to do "Request order start": `ARC`, `PO`; I'm sorry to say this, but at the moment you've got no roles in this project

**Comment by olegmoz** [comment]
@rultor release, tag=`0.25`

**Comment by 0crat** [comment]
Job `gh:artipie/asto#231` is not assigned, can't get performer
