### ISSUE TITLE
Cache verification

### ISSUE THREAD

**Issue by g4s8** [artipie/asto#233]
Add additional parameter for cache to verify it's content. It'll be useful when the client knows hash-sums of cached data and want's to verify it before downloading.

Related to https://github.com/artipie/maven-adapter/issues/146

**Comment by g4s8** [comment]
@rultor release, tag=`0.24`

**Comment by 0crat** [comment]
Job was finished in 42 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@f4d970db-062a-4a00-a6aa-acaa32bbc384, thread: PQ-CT2E6TK9B
com.zerocracy.farm.ruled.RdRules[130] java.lang.IllegalStateException: http://datum.zerocracy.com/latest/rules/pm/no-lost-boosts.xsl says: The boost for job "gh:artipie/asto#233" exists in boosts.xml, but the job is absent in the WBS among 59 jobs.
```

[0.54.5](https://github.com/zerocracy/farm): CID: [fc2053ac-7924-4d0f-a533-8f29b25c0f24](https://www.0crat.com/footprint/CT2E6TK9B/fc2053ac-7924-4d0f-a533-8f29b25c0f24), Type: "Remove job from WBS"
