### ISSUE TITLE
Implement storage transactions using StorageLock

### ISSUE THREAD

**Issue by olegmoz** [artipie/asto#237]
Basic transaction functions may be implemented using `StorageLock` class to acquire lock for specified keys and so avoid concurrent access to locked data

**Comment by 0crat** [comment]
You @olegmoz[/z](https://www.0crat.com/u/olegmoz) need to have one of these roles in order to do "Request order start": `ARC`, `PO`; I'm sorry to say this, but at the moment you've got no roles in this project

**Comment by 0crat** [comment]
Job `gh:artipie/asto#237` is not assigned, can't get performer

**Comment by olegmoz** [comment]
@rultor release, tag=`0.27`
