### ISSUE TITLE
Reactive lock to work better with RxStorage

### ISSUE THREAD

**Issue by olegmoz** [artipie/asto#246]
ASTO library provides `RxStorage` wrapper to use instead of `Storage` and it is used in adapters. When using with `Lock` it is needed to adapt this kind of storage manually. It would be nice to have such adapter ready in library

**Comment by 0crat** [comment]
You @olegmoz[/z](https://www.0crat.com/u/olegmoz) need to have one of these roles in order to do "Request order start": `ARC`, `PO`; I'm sorry to say this, but at the moment you've got no roles in this project

**Comment by 0crat** [comment]
Job `gh:artipie/asto#246` is not assigned, can't get performer
