### ISSUE TITLE
StorageLock fails acquire because of deleted proposals

### ISSUE THREAD

**Issue by olegmoz** [artipie/asto#260]
`StorageLock` reads proposals list and tries to read their content for expiration time after that. However proposals might be missing already and it causes `acquire` method to fail without good reason. This case should could be handled by additional check for existance of proposal value in `Storage` if `value` method has failed.

**Comment by 0crat** [comment]
You @olegmoz[/z](https://www.0crat.com/u/olegmoz) need to have one of these roles in order to do "Request order start": `ARC`, `PO`; I'm sorry to say this, but at the moment you've got no roles in this project

**Comment by olegmoz** [comment]
@rultor release, tag=`0.28`

**Comment by 0crat** [comment]
Job `gh:artipie/asto#260` is not assigned, can't get performer
