### ISSUE TITLE
Extend TestResource with method to add files to storage

### ISSUE THREAD

**Issue by olenagerasimova** [artipie/asto#261]
In maven-adapter it's often required to copy files from specified resources folder to storage, so let's add such method to `TestResource`.

**Comment by 0crat** [comment]
@olegmoz[/z](https://www.0crat.com/u/olegmoz) the issue is closed not by @olenagerasimova[/z](https://www.0crat.com/u/olenagerasimova) (its creator); I won't close the order; please, re-open it and ask @olenagerasimova[/z](https://www.0crat.com/u/olenagerasimova) to close it

**Comment by olenagerasimova** [comment]
@rultor release, tag=`0.27.1`
