### ISSUE TITLE
Transactions support

### ISSUE THREAD

**Issue by Sammers21** [artipie/asto#27]
Asto should support transactions in order to guarantee atomic updates of several keys.

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by 0crat** [comment]
You can't do "Request order start", unless you have one of these roles: `ARC`, `PO`; current roles of @sammers21[/z](https://www.0crat.com/u/sammers21) are: `DEV`

**Comment by 0crat** [comment]
Job `gh:artipie/asto#27` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
