### ISSUE TITLE
`Cache` implementation

### ISSUE THREAD

**Issue by olenagerasimova** [artipie/asto#284]
Let's add implementation of `Cache` to always load content from remote and cache it to storage. Content should be obtained from storage cache only if remote failed to return item.

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@3edca2e5-844b-4319-acde-b5f490b23a71, thread: PQ-CT2E6TK9B
com.amazonaws.http.AmazonHttpClient$RequestExecutor[1359] com.amazonaws.ResetException: Failed to reset the request input stream;  If the request involves an input stream, the maximum stream buffer size can be configured via request.getRequestClientOptions().setReadLimit(int)
java.io.BufferedInputStream[170] java.io.IOException: Stream closed
```

[0.54.5](https://github.com/zerocracy/farm): CID: [1d9faa68-bd6e-4257-bfed-7c0f3542aaf8](https://www.0crat.com/footprint/CT2E6TK9B/1d9faa68-bd6e-4257-bfed-7c0f3542aaf8), Type: "Award points were added"

**Comment by olenagerasimova** [comment]
@rultor release, tag=`0.30`

**Comment by 0crat** [comment]
@olegmoz[/z](https://www.0crat.com/u/olegmoz) the issue is closed not by @olenagerasimova[/z](https://www.0crat.com/u/olenagerasimova) (its creator); I won't close the order; please, re-open it and ask @olenagerasimova[/z](https://www.0crat.com/u/olenagerasimova) to close it
