### ISSUE TITLE
Cache should return Optional of Content

### ISSUE THREAD

**Issue by olenagerasimova** [artipie/asto#286]
Let's change signature of `Cache#load` method to return `CompletionStage` of Optional with Content as it's possible there will not be any content to return in cases we do not have requested data in cache and remote return any unsuccessful response.

**Comment by 0crat** [comment]
Job `gh:artipie/asto#286` is not assigned, can't get performer

**Comment by olenagerasimova** [comment]
@rultor release, tag=`0.32`
