### ISSUE TITLE
Alternative for CompletableFuture.failedFuture

### ISSUE THREAD

**Issue by olegmoz** [artipie/asto#287]
In Java 8 there is no quick way to create future that is failed from the start. It would be useful to create such class in ASTO and use it here and in other adapters

**Comment by 0crat** [comment]
You @olegmoz[/z](https://www.0crat.com/u/olegmoz) need to have one of these roles in order to do "Request order start": `ARC`, `PO`; I'm sorry to say this, but at the moment you've got no roles in this project

**Comment by olegmoz** [comment]
@rultor release, tag=`0.30`

**Comment by olegmoz** [comment]
@rultor release, tag=`0.31`

**Comment by 0crat** [comment]
Job `gh:artipie/asto#287` is not assigned, can't get performer
