### ISSUE TITLE
Move ContentAs from artipie

### ISSUE THREAD

**Issue by olenagerasimova** [artipie/asto#293]
Let's move `ContentAs` class here from artipie.

**Comment by olenagerasimova** [comment]
@rultor release, tag=`0.33`

**Comment by 0crat** [comment]
@olegmoz[/z](https://www.0crat.com/u/olegmoz) the issue is closed not by @olenagerasimova[/z](https://www.0crat.com/u/olenagerasimova) (its creator); I won't close the order; please, re-open it and ask @olenagerasimova[/z](https://www.0crat.com/u/olenagerasimova) to close it

**Comment by olenagerasimova** [comment]
@rultor release, tag=`0.33.1`

**Comment by 0crat** [comment]
@olenagerasimova[/z](https://www.0crat.com/u/olenagerasimova) resigned from [#293](https://github.com/artipie/asto/issues/293), since the job is not in scope anymore
