### ISSUE TITLE
FileStorage: Delete empty directories

### ISSUE THREAD

**Issue by olenagerasimova** [artipie/asto#302]
File storage should delete empty directories while deleting files

**Comment by 0crat** [comment]
Job was finished in 23 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))

**Comment by olenagerasimova** [comment]
@rultor release, tag=`0.33.7`

**Comment by olenagerasimova** [comment]
@rultor release, tag=`0.33.8`
