### ISSUE TITLE
Base Artipie exception

### ISSUE THREAD

**Issue by g4s8** [artipie/asto#311]
Our customers work with many Artipie adapters as SDK libraries, each adapter works with exception differently. It'd be more convenient to have a base exception type to throw from SDK methods of each adapter and some additional sub-classes to provide more details (e.g. http-exception with status codes, etc).

The open questions are:
 - What is the correct repo/project to place such exception?
 - What is the name of the class (maybe `ArtipieException`)?
 - Checked or unchecked?

**Comment by g4s8** [comment]
@artipie/members WDYT?

**Comment by genryxy** [comment]
@g4s8 
`artipie` module looks the best but adapters do not have this dependency, therefore it should be some module which is used in all others (`http` or `asto`)
In my opinion, the name of class for exception is appropriate.
Unchecked exception looks better.

**Comment by ChGen** [comment]
* I think this exception should be in `asto` module or in some new module which will be common dependency for all adapters.
* `ArtipieException` is good name for this base exception class
* Checked exception is overkill here, and in general it's not recommended.

**Comment by olenagerasimova** [comment]
@rultor release, tag=`0.36`

**Comment by g4s8** [comment]
@rultor stop

**Comment by g4s8** [comment]
@olenagerasimova it's a breaking change, since it requires changes on client code, this is why new exception has `since 1.0` flag

**Comment by g4s8** [comment]
@rultor release, tag=`1.0.0`
