### ISSUE TITLE
Create storage implementation for benchmarks

### ISSUE THREAD

**Issue by g4s8** [artipie/asto#314]
## Problem

Each adapter benchmark requires common logic for storage setup: it copies test data to storage, then run benchmark, then reset storage to initial state to run benchmark again. Using JMH, we can run multiple benchmarks simultaneously but in that case we need to construct and initialize a new storage for each test run, it may affect other benchmarks. Share one storage for all benchmarks is also not an option, since each run can write/delete/move data in storage.

## Proposal

So I'm proposing this solution: make a new copy-on-write storage implementation with a base shared read-only storage as a back-end, local isolated storage for write operations and a hash-table for deleted flags. So each JMH benchmark iteration will create and initialize a base storage with test data packages as a base read-only storage, and each benchmark run will create a new isolated local storage with base storage back-end for benchmark and a fresh table for delete-flags.
 - Each **read** operation first checks the deleted flags table and if flag exist, then fails with not-found exception, if deleted flag doesn't exist, then it tries to read from local storage, if local storage doesn't have such key, then go to shared back-end
 - Each **write** operation goes to local storage and rest deleted flag if exist
 - Each **delete** operation just put deleted flag to table
 - Each **move** operation tries to move data in local storage. If local key not found, then it copies data from shared storage to local first

Using `InMemory` storage as a back-end, we can optimize move operations by using data byte-array references for copying: since `InMemory` implementation doesn't perform in-place modification in data, we can safely copy byte-array reference from back-end to local storage on move.

### Architecture

```
+-----------+
|  Storage  |
+-----------+
      |
      V
+----------------+
|  BenchStorage  |
+----------------+
| backEnd        +------> InMemoryStorage
| local          +------> Map<Key, byte[]>
| deleted        +------> Set<Key>
+----------------+
```

**Comment by g4s8** [comment]
@artipie/members what do you think?

**Comment by genryxy** [comment]
@g4s8 I'd suggest to specify that it would be better to use `ConcurrentHashSet` from guava instead of `HashSet` to avoid synchronizing for each operation as we decided in Helm. 
And the same for `ConcurrentHashMap` instead of `HashMap`. Or `NavigableMap` if method `list` should be implemented.
Also I have concern about **move** operation because it seems there is no way to get reference on byte array for existed implementation of `InMemoryStorage`.

**Comment by genryxy** [comment]
@g4s8 could you please release a new version
