### ISSUE TITLE
GzipCompressorInputStream can stuck sometimes

### ISSUE THREAD

**Issue by g4s8** [artipie/asto#343]
`GzipCompressorInputStream` can stuck on sometimes, maybe it depends on environment. This happens not often, but I still can reproduce it (by running the test multiple times) on macOS (on win build sometimes fails too).
 
The example is from `rpm`, there I need to update three metadata files, I'm doing in similar way.

We need to isolate the problem and make a minimal reproducible test for this.

Check this discussion for more details.
_Originally posted by @olenagerasimova in https://github.com/artipie/asto/issues/340#issuecomment-942229033_

**Comment by dgarus** [comment]
@olenagerasimova hi!
Is this issue still actual?

**Comment by olenagerasimova** [comment]
@dgarus no, closing
