### ISSUE TITLE
Test that operations are properly logged in LoggingStorage. We are currently testing that...

### ISSUE THREAD

**Issue by 0pdd** [artipie/asto#345]
The puzzle `186-fbb1def2` from #186 has to be resolved: 

https://github.com/artipie/asto/blob/7e07dd52496ceb2dae39a264a37336e04902b2a3/src/test/java/com/artipie/asto/LoggingStorageTest.java#L19-L22

The puzzle was created by @baudoliver7 on 27-Oct-21. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by kirill-h5i** [comment]
@g4s8 assign to @baudoliver7

**Comment by 0pdd** [comment]
@0pdd the puzzle [#370](https://github.com/artipie/asto/issues/370) is still not solved.

**Comment by 0pdd** [comment]
@0pdd the only puzzle [#370](https://github.com/artipie/asto/issues/370) is solved here.
