### ISSUE TITLE
Remove items from the storage by prefix key

### ISSUE THREAD

**Issue by olenagerasimova** [artipie/asto#348]
Very often it's necessary to remove items from storage by some key prefix:
```
private CompletableFuture<Void> remove(final Key key) {
        return this.asto.list(key).thenCompose(
            list -> CompletableFuture.allOf(
                list.stream().map(this.asto::delete)
                    .toArray(CompletableFuture[]::new)
            )
        );
    }
```
Such methods are duplicated a lot in different adapters. I'd suggest to add class for this operation
(the example can be improved by checking that item exists before performing remove operation).

**Comment by olenagerasimova** [comment]
@g4s8 please, pass this issue to freelancers

**Comment by baudoliver7** [comment]
@olenagerasimova I'm in charge of this issue.
I can't find the piece of code mentioned in description.

**Comment by olenagerasimova** [comment]
@baudoliver7 in this repo this piece of code is not present, it's very popular in the adapters (rpm and docker at least)

**Comment by baudoliver7** [comment]
@olenagerasimova Ah, I see now. Thx :)
