### ISSUE TITLE
Key.From should use List instead of Iterable

### ISSUE THREAD

**Issue by Nimmaster** [artipie/asto#35]
`com.artipie.asto.Key.From` [stores key parts](https://github.com/artipie/asto/blob/master/src/main/java/com/artipie/asto/Key.java#L80) as `Iterable`

Classes `Iterable` (and `Collection` in constructor args) do not guarantee iteration order. We rely on particular insertion order when joining the iterable into a string.

**Comment by olegmoz** [comment]
Fixed in https://github.com/artipie/asto/issues/69

**Comment by 0crat** [comment]
Job `gh:artipie/asto#35` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
