### ISSUE TITLE
List items of `SubStorage`

### ISSUE THREAD

**Issue by olenagerasimova** [artipie/asto#351]
I found two problems with `SubStorage`:
1) Complete lack of tests
2) `list` operation does work correctly in some cases: when `SubStorage` is created with `Ket.ROOT` as prefix, `list` removes first met `/` symbol, thus returning not existing items. For example, if the sub storage contains `abc/xyz/hello.txt`, then list by `abc` key will return `abcxyz/hello.txt`

**Comment by 0pdd** [comment]
@olenagerasimova the puzzle [#354](https://github.com/artipie/asto/issues/354) is still not solved.

**Comment by 0pdd** [comment]
@olenagerasimova the only puzzle [#354](https://github.com/artipie/asto/issues/354) is solved here.
