### ISSUE TITLE
Use files-adapter as storage proxy

### ISSUE THREAD

**Issue by g4s8** [artipie/asto#405]
Implement `Storage` as `ArtipieStorage` for artipie/files-adapter via HTTP, see https://github.com/artipie/files-adapter/issues/106 for details, `ArtipieStorage` HTTP client (from artipie/http-client) in constructor and performs all operations via this client.

**Comment by dgarus** [comment]
@g4s8 
`artipie/http-client` has `asto` dependency, so `artipie/http-client` dependency in `asto` is cyclic.
Is it ok?

**Comment by g4s8** [comment]
> @g4s8 `artipie/http-client` has `asto` dependency, so `artipie/http-client` dependency in `asto` is cyclic. Is it ok?

@dgarus maybe we can exclude this dependency?

**Comment by dgarus** [comment]
> @dgarus maybe we can exclude this dependency?
 @g4s8  Do you mean exclude `asto` from `file-adapter`?
Could you create a task to investigate/do this?

**Comment by g4s8** [comment]
> > @dgarus maybe we can exclude this dependency?
>  
> 
> @g4s8  Do you mean exclude `asto` from `file-adapter`?
> Could you create a task to investigate/do this?
>  
> 
> 

@dgarus no, I mean excluding asto dependency from http-client

**Comment by dgarus** [comment]
> @dgarus no, I mean excluding asto dependency from http-client

@g4s8 Yes, sorry. I made a typo.
Ok, Could you please create a task to do this and assign it to me?

**Comment by g4s8** [comment]
> > @dgarus no, I mean excluding asto dependency from http-client
> 
> @g4s8 Yes, sorry. I made a typo.
> Ok, Could you please create a task to do this and assign it to me?

@dgarus you can exclude it in maven dependency configuration: just add dependency names to exclude section of the dependency in pom
