### ISSUE TITLE
Use buffered publisher flow

### ISSUE THREAD

**Issue by g4s8** [artipie/asto#41]
Use `ByteBuffer` or custom buffer class instead of `Byte` in `Storage` interface.

**Comment by g4s8** [comment]
@0crat assign @Sammers21

**Comment by 0crat** [comment]
> @0crat assign @Sammers21  ([here](https://github.com/artipie/asto/issues/41#issuecomment-583380540))

@g4s8 The job [#41](https://github.com/artipie/asto/issues/41) assigned to @sammers21[/z](https://www.0crat.com/u/sammers21), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/470937a9-4efa-4b20-9540-ccdc93243138); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); we should be aware that @sammers21[/z](https://www.0crat.com/u/sammers21) is on vacation; this ticket may be delayed; there will be no monetary reward for this job

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by 0crat** [comment]
Order was finished: +30 point(s) just awarded to @sammers21[/z](https://www.0crat.com/u/sammers21)
