### ISSUE TITLE
Fix test for `LoggingStorage`

### ISSUE THREAD

**Issue by olenagerasimova** [artipie/asto#413]
Let's fix `LoggingStorageTest`: after logging library updates, logger does not write into writer, configured in the test. Figure out how to deal with it and enable the test.

**Comment by baudoliver7** [comment]
@olenagerasimova hi, with pleasure ! :)

**Comment by olenagerasimova** [comment]
@baudoliver7 nice, waiting for PR :)

**Comment by baudoliver7** [comment]
@olenagerasimova PR submitted [here ](https://github.com/artipie/asto/pull/420):)
