### ISSUE TITLE
Remeaining class affects buffer state on read

### ISSUE THREAD

**Issue by g4s8** [artipie/asto#43]
`Remaining` class affects underlying `ByteBuffer` on read operations.

**Comment by g4s8** [comment]
@0crat assign me

**Comment by 0crat** [comment]
> @0crat assign me ([here](https://github.com/artipie/asto/issues/43#issuecomment-584108466))

@g4s8 The job [#43](https://github.com/artipie/asto/issues/43) assigned to @g4s8[/z](https://www.0crat.com/u/g4s8), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/5653f027-d1c6-4cfd-82c6-742f3e32f11a); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by 0crat** [comment]
It is strongly discouraged to assign jobs to their creators, see [§19](http://www.zerocracy.com/policy.html#19): -15 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by Sammers21** [comment]
@g4s8 , `Remaining` should affect underlying `ByteBuffer`, since it is a read operation. Please, revert the changes in  #44 .

**Comment by g4s8** [comment]
> @g4s8 , `Remaining` should affect underlying `ByteBuffer`, since it is a read operation. Please, revert the changes in #44 .

@Sammers21 it will be fixed in scope of #47

**Comment by 0crat** [comment]
Job was finished in 21 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))

**Comment by 0crat** [comment]
Order was finished: +35 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)
