### ISSUE TITLE
FileStorage.save() method should overwrite existing data

### ISSUE THREAD

**Issue by olegmoz** [artipie/asto#46]
Now FileStorage does not allow overwriting existing value with `java.nio.file.FileAlreadyExistsException`.

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by 0crat** [comment]
@olegmoz[/z](https://www.0crat.com/u/olegmoz) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/CT2E6TK9B) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by olegmoz** [comment]
Bug was found in version 0.11.1, it happens that it cannot be reproduced in 0.13.0. Added unit test to verify that this important property of storage is supported in future releases.

**Comment by 0crat** [comment]
Job `gh:artipie/asto#46` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
