### ISSUE TITLE
tag missing problem

### ISSUE THREAD

**Issue by CChengjie** [artipie/asto#470]
I'm doing a research on tags .
We found that versions like **0.19.0** was released in Maven, but there was no corresponding tag in github, Can you help me with this?
1）What is the reason for tag's absence?

- a、This version code has problems, such as the loophole, compatibility and interface issues, etc.
- b、This version has functional problems, such as unreasonable function planning, basic function cannot be used
- c、Forgot to tag
- d、Don't care or is too trouble
- e、Don't care or is too trouble
- f、others，_

2） To solve this problem, we propose a method that can find the true commit of version to help developers quickly locate the problem code and fix the bug. Here are the possible true commits given by our method. Can you confirm whether or not the actual commits are included, and if not, which ones?

['b724f2725871de68ab8d271986449323842799af', '63ae78e7393bc0ebb51bdc510ed8231caa3646ea', '4e861522beee740b6ff15113443eec888a04f5e7', 'e81be094fbcd414618313408d5c69472d34d96a1']

i think it is same as 0.19.1 

♥ This question is very important to our research. Thank you for your time!

**Comment by olenagerasimova** [comment]
Hi @CChengjie ! Thank you for the concern, version 0.19.0 was release in 2020, now we cannot say what exactly happened, most probably there was some glitch. Please, use the latest version `v1.13.0`

**Comment by dgarus** [comment]
@CChengjie @olenagerasimova 
There is no problem, I close the issue
