### ISSUE TITLE
Add test coverage for BlockingStorage, RxStorage, RxStorageTransaction

### ISSUE THREAD

**Issue by olegmoz** [artipie/asto#55]

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by 0crat** [comment]
@olegmoz[/z](https://www.0crat.com/u/olegmoz) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/CT2E6TK9B) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by 0pdd** [comment]
@olegmoz the puzzle [#383](https://github.com/artipie/asto/issues/383) is still not solved.

**Comment by 0pdd** [comment]
@olegmoz the only puzzle [#383](https://github.com/artipie/asto/issues/383) is solved here.
