### ISSUE TITLE
FileStorage.exists() should not return `true` for directories

### ISSUE THREAD

**Issue by olegmoz** [artipie/asto#64]
Now `FileStorage.exists()` returns `true` for directories, so it is possible to have only key `a/b/c` in repository, but `exists()` will return `true` for key `a/b`. And at the same time `value()` methods will fail for this key. This behavior is inconsistent.

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by 0crat** [comment]
@olegmoz[/z](https://www.0crat.com/u/olegmoz) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/CT2E6TK9B) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by 0crat** [comment]
Job `gh:artipie/asto#64` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
