### ISSUE TITLE
New storage types support [waiting for approval]

### ISSUE THREAD

**Issue by g4s8** [artipie/asto#67]
Add new `Storage` implementations for cloud providers:
 - AWS S3
 - Ali Cloud
 - Huawei Cloud

**Comment by Guseyn** [comment]
@g4s8 started doing Ali Cloud, plz merge skeleton #157

**Comment by g4s8** [comment]
@Guseyn what happens with google-cloud implementation

**Comment by g4s8** [comment]
Done

**Comment by 0crat** [comment]
Job `gh:artipie/asto#67` is not assigned, can't get performer
