### ISSUE TITLE
Key improvements

### ISSUE THREAD

**Issue by olegmoz** [artipie/asto#69]
Some improvements proposed for `Key` class:
* `parts` field should be of type `List`, because naturally it is ordered and has limited size.
* Add `Key.From()` constructor to create `Key` from `/`-delimited string. It is useful to create `Key` from strings created by `Key.string()` method and from URI path which is going to be very useful in adapters.
* Part string should not contain `/` symbol, otherwise it cannot be to string and from string.

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by 0crat** [comment]
@olegmoz[/z](https://www.0crat.com/u/olegmoz) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/CT2E6TK9B) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by 0crat** [comment]
Job `gh:artipie/asto#69` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope

**Comment by g4s8** [comment]
@rultor release, tag=`0.13.4`
