### ISSUE TITLE
S3 storage implementation

### ISSUE THREAD

**Issue by olegmoz** [artipie/asto#87]
Create `Storage` implementation that stores data in S3.

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by 0crat** [comment]
@olegmoz[/z](https://www.0crat.com/u/olegmoz) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/CT2E6TK9B) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by 0pdd** [comment]
@olegmoz the puzzle [#96](https://github.com/artipie/asto/issues/96) is still not solved.

**Comment by 0pdd** [comment]
@olegmoz 2 puzzles [#108](https://github.com/artipie/asto/issues/108), [#96](https://github.com/artipie/asto/issues/96) are still not solved.

**Comment by 0pdd** [comment]
@olegmoz the puzzle [#108](https://github.com/artipie/asto/issues/108) is still not solved; solved: [#96](https://github.com/artipie/asto/issues/96).

**Comment by g4s8** [comment]
@rultor release, tag=`0.16`

**Comment by 0pdd** [comment]
@olegmoz 2 puzzles [#108](https://github.com/artipie/asto/issues/108), [#186](https://github.com/artipie/asto/issues/186) are still not solved; solved: [#96](https://github.com/artipie/asto/issues/96).

**Comment by g4s8** [comment]
@olegmoz I suppose S3 storage is working now, can we close this ticket?

**Comment by olegmoz** [comment]
@g4s8 sure, closing it

**Comment by 0crat** [comment]
Job `gh:artipie/asto#87` is not assigned, can't get performer

**Comment by 0pdd** [comment]
@olegmoz 2 puzzles [#108](https://github.com/artipie/asto/issues/108), [#370](https://github.com/artipie/asto/issues/370) are still not solved; solved: [#186](https://github.com/artipie/asto/issues/186), [#345](https://github.com/artipie/asto/issues/345), [#96](https://github.com/artipie/asto/issues/96).

**Comment by 0pdd** [comment]
@olegmoz the puzzle [#108](https://github.com/artipie/asto/issues/108) is still not solved; solved: [#186](https://github.com/artipie/asto/issues/186), [#345](https://github.com/artipie/asto/issues/345), [#370](https://github.com/artipie/asto/issues/370), [#96](https://github.com/artipie/asto/issues/96).

**Comment by 0pdd** [comment]
@olegmoz the puzzle [#442](https://github.com/artipie/asto/issues/442) is still not solved.

**Comment by 0pdd** [comment]
@olegmoz the puzzle [#unknown]() is still not solved; solved: [#442](https://github.com/artipie/asto/issues/442).
