### ISSUE TITLE
Pass value content length along with content bytes in `Storage`

### ISSUE THREAD

**Issue by olegmoz** [artipie/asto#90]
Now `Storage.save()` method accepts flow of bytes and there is no way to know total content size before reading them all. But actual content length is often known to storage client and might be used by storage implementations for some optimization (such as allocating right amount of memory, choosing right uploading strategy etc).
Same goes for `value()` method. Storage usually knows content length in advance and may pass it before actual data is read to make things easier for consumer.

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by 0crat** [comment]
@olegmoz[/z](https://www.0crat.com/u/olegmoz) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/CT2E6TK9B) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by 0crat** [comment]
Job `gh:artipie/asto#90` is not assigned, can't get performer
