### ISSUE TITLE
MultipartUpload.java:83-85: Refactor MultipartUpload...

### ISSUE THREAD

**Issue by 0pdd** [artipie/asto#96]
The puzzle `87-0ebc33ba` from #87 has to be resolved: 

https://github.com/artipie/asto/blob/4d5bfd390bd40e16e5f7b2579a18c5c6f215d6fc/src/main/java/com/artipie/asto/s3/MultipartUpload.java#L83-L85

The puzzle was created by @olegmoz on 04-Mar-20. 

Estimate: 60 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by 0pdd** [comment]
The puzzle `87-0ebc33ba` has disappeared from the source code, that's why I closed this issue.

**Comment by 0crat** [comment]
Job `gh:artipie/asto#96` is not assigned, can't get performer
